ALTER TYPE "InterviewType" ADD VALUE IF NOT EXISTS 'SYSTEM_DESIGN';
ALTER TYPE "InterviewType" ADD VALUE IF NOT EXISTS 'AI_ML';
ALTER TYPE "InterviewType" ADD VALUE IF NOT EXISTS 'MIXED';

ALTER TABLE "Interview" ADD COLUMN "adaptiveState" JSONB;
